# Generated by Django 5.0.6 on 2024-06-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_scrapejob_scraperesult_delete_scrapingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='contracts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='official_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='socials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
